### ISSUE TITLE
get방식만 지원되나요?

### ISSUE THREAD

**Issue by hulint** [kijin/postcodify#4]
안녕하세요~

이번에 API를 적용하게 됐습니다.

저희 소스에서 $.ajaxSetting을 통해서 모든 ajax 통신은 POST로 submit되도록 적용하고 있는데,

API는 GET방식만 지원하고 있어서 POST방식을 지원하고 있지 않는거 같습니다.

소스를 보니 ajax를 사용하고 있는데 type을 GET으로 지정해주면 다른 설정없이 사용할거 같습니다.

**Comment by kijin** [comment]
지적해 주셔서 감사합니다. `$.ajaxSetting` 기본값을 바꿔 사용하는 경우까지는 생각을 못했네요. 다음 버전에서 고치도록 하겠습니다.
