### ISSUE TITLE
jQuery 플러그인: 로컬 페이지에서 검색이 안되는 문제.

### ISSUE THREAD

**Issue by zn** [kijin/postcodify#6]
![default](https://cloud.githubusercontent.com/assets/830515/7352707/e07af5b0-ed48-11e4-9b2f-32375883ba4d.png)

안녕하세요. 제가 개인적으로 만드는 프로그램에 jQuery 플러그인으로 적용하고자 합니다.

그 프로그램이 nw.js(node-webkit)를 가지고 만드는 데, 로컬처럼 작동을 해서 그런지 `//api.poesis.kr`로 요청을 하는게 `file://api.poesis.kr`로 가버리는 현상이 발생합니다. 이처럼 웹 사이트가 아닌 경우에도 작동이 되면 더욱 좋을 것 같습니다.

좋은 프로그램 만들어 주셔서 감사합니다. 잘 쓰도록 하겠습니다.

**Comment by kijin** [comment]
jQuery 플러그인을 사용할 때 `api` 및 `apiBackup` 설정을 변경해 주시면 됩니다.

https://postcodify.poesis.kr/guide/jquery_plugin

    $("선택자").postcodify({
        api: "https://api.poesis.kr/post/search.php",
        apiBackup: "https://api.poesis.co.kr/post/search.php",
        // 기타 다른 설정
    });

**Comment by zn** [comment]
답변 감사합니다. 문서에 답이 있는데 제대로 읽지 못한 제 잘못이었네요... 번거롭게 해서 죄송합니다.
