### ISSUE TITLE
이번 업데이트 후 팝업창내용이 잘려서 나옵니다.

### ISSUE THREAD

**Issue by llois** [kijin/postcodify#7]
안녕하세요? 먼저 유용하고 훌륭한 플러그인을 만들어 주셔서 감사합니다.

잘 사용중에 있었는데

이번에 업데이트가 있으셨는지 검색 팝업창이 디자인이 미려하게 바꾸어 졌더라구요.

그런데 업데이트 후 팝업창 내용이 첨부한 그림과 같이 잘려서 나오는 현상이 발생합니다
(editor로 보니 144px로 고정되더군요)

이 상황에서 기능은 정상적으로 작동을 하고

브라우저크기를 변경하면 즉시 정상적으로 펼쳐집니다.

왜 이러는지 이유를 알 수 있을까요?

(IE, 크롬 모두 동일 합니다)
(참고링크 : http://hongcoffee.co.kr/member/JoinStep3)

![postify_error](https://cloud.githubusercontent.com/assets/10164454/8499248/a2cf39c6-21cb-11e5-9e38-055bad571dec.png)

**Comment by kijin** [comment]
검색단추 부분도 곡선이 부드럽지 않고 사각형이 삐죽 튀어나왔네요.

공식 사이트나 제가 관리하는 다른 사이트에서는 아무 문제가 없는 것으로 보아, 님의 사이트에서 사용하는 CSS 일부가 이번에 새로 적용한 Postcodify의 CSS와 충돌하는 것 같습니다. 일단 부트스트랩이 의심되긴 하는데, 좀더 살펴보고 알려드리겠습니다.

**Comment by llois** [comment]
네 부트스트랩과 axisj 가 적용되어 있습니다!

감사합니다!!

2015년 7월 3일 금요일, Kijin Sung<notifications@github.com>님이 작성한 메시지:

**Comment by kijin** [comment]
살짝 업데이트를 했습니다. Ctrl+F5를 눌러 새로고침해 보세요.

CDN의 특성상, 변경된 내역이 모든 사용자에게 전달되기까지는 하루 정도가 걸릴 수도 있습니다.

**Comment by llois** [comment]
우와!!!
바로 수정 되서 잘 됩니다!! 검색 버튼 찌그러진것도 잘 되네요!!

Github 처음 문의글인데 너무 친절하고 빠른 답변과 대처 감사 드립니다!!!

Star 눌렀습니다 ㅎㅎㅎ 감사합니다!!
