### ISSUE TITLE
/lib/classes/indexer/update.php 758 line error

### ISSUE THREAD

**Issue by ktj4820** [kijin/postcodify#8]
update.php 758 line  을 보면 신 우편번호체계에서 배열이 변경되듯합니다. 
매핑에 대한 정의가 없어서 매핑이 어렵네요. 

수정부탁드립니다.

**Comment by kijin** [comment]
어떤 에러가 발생하는지 자세히 알려주시면 해결에 도움이 되겠습니다.

**Comment by ktj4820** [comment]
안녕하세요. 

php indexer.php update 명령어 실행시 
아래와 같은 오류가 나오고 있습니다. 

![image](https://cloud.githubusercontent.com/assets/1456050/10044711/0778815a-6238-11e5-93d7-87d580b28098.png)


압축파일을 풀어 AlterD....TL_SCCO_MVMN.TXT파일을 보니  

update.php 674 line의 양식과 포멧이 틀린듯합니다.

**Comment by ktj4820** [comment]
AlterD.JUSUBM.20150802.TI_SCCO_MVMN.TXT
==============================================================================
4213039025|강원도|원주시|신림면|성남리|0|116|3|421303013005|0|284|0|24968|63
4213039025|강원도|원주시|신림면|성남리|0|118|0|421303013005|0|284|0|24969|63
4213039025|강원도|원주시|신림면|성남리|0|118|1|421303013005|0|284|0|24970|63
4213011100|강원도|원주시|우산동||0|246|21|421304457286|0|30|12|26816|31
4511310300|전라북도|전주시 덕진구|인후동1가||0|866|12|451134601016|0|10|0|5765|63
4511310300|전라북도|전주시 덕진구|인후동1가||0|866|12|451134601016|0|10|0|20904|31
==============================================================================

update.php line 667 ~ 677
                // 1천 건 단위로 읽어와서 도로명주소 단위로 분류한다.
                
                $entries = array();
                for ($i = 0; $i < 1000; $i++)
                {
                    $entry = $zip->read_line();
                    if ($entry === false) break;
                    $key = $entry->road_id . '|' . $entry->num_major . '|' . $entry->num_minor . '|' . $entry->is_basement;
                    $entries[$key][] = array($entry->dongri, $entry->jibeon_major, $entry->jibeon_minor, $entry->is_mountain);
                    unset($entry);
                }

**Comment by kijin** [comment]
행자부에서 배포되는 파일 포맷은 Postcodify 3.1 릴리즈 이후 변경된 바가 없습니다.

`TI_SCCO_MVMN.TXT` 파일의 내용은 `Postcodify_Parser_NewJibeon` 클래스에서 파싱하여 `$entry`라는 오브젝트로 변환하고 있으므로, 원본파일의 포맷은 신경쓰실 필요가 없습니다. 이후에 `$key`를 만들어 쓰는 것도 업데이트 스크립트 내에서 통용되는 포맷일 뿐, 원본파일의 포맷과는 무관합니다.

말씀하신 에러는 `$key`를 디코딩하는 과정에서 건물번호 부번(`$num_minor`)이 빈 문자열로 변환되기 때문에 발생하는 것 같습니다. 부번이 없는 경우에는 `null`로 처리되어야 하는데, `explode()` 함수를 사용하니까 빈 문자열이 되어 버렸네요. 

제 서버에서는 빈 문자열이라도 문제가 발생하지 않아서 오늘자 업데이트까지 정상적으로 적용되었습니다만, 서버 설정에 따라서는 에러가 발생할 수도 있겠습니다.

혹시 `explode()` 바로 다음인 689줄과 690줄 사이에 아래의 코드를 추가하면 어떤 변화가 있는지 확인 부탁드립니다.

    if (!$num_minor) $num_minor = null;

**Comment by ktj4820** [comment]
해당 이슈는 보내주신 것으로 잘 해결되었습니다. 감사합니다. 

그런데 건물정보부분에서 560 Line에서 아래와 같은 에러가 발생합니다. 

환경은 Centos6 , php 5.3.3 입니다. 

![image](https://cloud.githubusercontent.com/assets/1456050/10062441/a08936d6-629d-11e5-9fe3-24d7910fef1e.png)

**Comment by kijin** [comment]
`sql_mode`를 엄격하게 설정해 놓고 쓰시는 모양이네요 ㅎㅎ

좀더 제대로 된 패치를 적용하였으니, 어제 테스트를 위해 수정하신 것은 원래대로 되돌리고 최신 커밋을 `git pull`해서 사용해 보시기 바랍니다.

**Comment by kijin** [comment]
더이상 문제가 없다면 이 이슈는 닫겠습니다.

**Comment by ktj4820** [comment]
sql_mode를 엄격하게 놓아서 나는 문제였군요 ㅠㅠ 
해결감사합니다.
