### ISSUE TITLE
Unreachable statement in query.php line 149

### ISSUE THREAD

**Issue by hyungsul** [kijin/postcodify#9]
$keyword 가 한 글자의 한글일 경우에는, 건너 뛰기때문에, 

Line 147 에서의 

```php
($keyword === '읍' || $keyword === '면')
```

조건은 항상 거짓이 됩니다. 따라서 Line 149 statement 는 실행될 수 없는 부분입니다.
이 부분에 대한 이해가 부족한데, 어느 경우인지 설명해주실 수 있으신가요?

감사합니다.

**Comment by kijin** [comment]
시군구 명칭과 그 아래 읍면 명칭이 같은 일부 농어촌 지역에서는 주소를 아래와 같이 줄여쓰는 관례가 있습니다. 엄밀히 말하면 틀린 표기법이지만 일상적으로 많이 통용됩니다.

> 강원도 양양군.읍 서문리 (강원도 양양군 양양읍 서문리)
> 강원도 철원군·읍 화지리 (강원도 철원군 철원읍 화지리)

예전에는 마침표, 가운뎃점 등을 공백으로 변환했기 때문에 이렇게 검색하면 "읍" 또는 "면"이 별도의 키워드로 떨어져 나왔습니다. 그러나 최근 버전에서는 마침표를 지우고 양쪽을 붙여버리니까 별도의 처리가 필요하지 않겠네요. "군"과 "읍"이 붙은 경우의 처리는 바로 그 윗부분에서 해주고 있고요.

실제 사용자들의 검색 패턴에 따라 키워드 분석 방식을 계속해서 조정해 왔기 때문에 이렇게 예전 방식의 흔적이 남아 있는 곳이 여러 군데 될 겁니다. 한번 쭉 둘러보고 더이상 필요하지 않은 조건식은 정리하도록 하겠습니다. 소스를 꼼꼼하게 봐주셔서 감사합니다 ^^

**Comment by hyungsul** [comment]
상세한 답변 감사드립니다! 사용자 검색로그를 바탕으로 개선해 오셨군요. 멋지네요!
